@startuml

title __FACTORY's Class Diagram__\n

  namespace org.simonworks.projects.factory {
    class org.simonworks.projects.factory.BeanCreationException {
        + BeanCreationException()
    }
  }
  

  namespace org.simonworks.projects.factory {
    interface org.simonworks.projects.factory.BeanCreationPhase {
        {abstract} + apply()
    }
  }
  

  namespace org.simonworks.projects.factory {
    interface org.simonworks.projects.factory.BeanFactory {
        {abstract} + create()
        {abstract} + create()
    }
  }
  

  namespace org.simonworks.projects.factory {
    class org.simonworks.projects.factory.ConfigurationPhase {
        + apply()
    }
  }
  

  namespace org.simonworks.projects.factory {
    class org.simonworks.projects.factory.DefaultBeanFactory {
        {static} - LOGGER : Logger
        - creationPipeline : List<BeanCreationPhase>
        + DefaultBeanFactory()
        + DefaultBeanFactory()
        + create()
        + create()
        - applyCreationPipeline()
    }
  }
  

  namespace org.simonworks.projects.factory {
    class org.simonworks.projects.factory.PostConstructPhase {
        + apply()
    }
  }
  

  org.simonworks.projects.factory.ConfigurationPhase .up.|> org.simonworks.projects.factory.BeanCreationPhase
  org.simonworks.projects.factory.DefaultBeanFactory .up.|> org.simonworks.projects.factory.BeanFactory
  org.simonworks.projects.factory.PostConstructPhase .up.|> org.simonworks.projects.factory.BeanCreationPhase


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
